services:
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    ports:
      - "8020:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./data/open-webui:/app/backend/data
    restart: unless-stopped
