---
services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - ./.data/config:/config
    ports:
      - 3033:3000
      - 3034:3001
    shm_size: "1gb"
    restart: unless-stopped
